version: '3'
services:

  php:
#    image: php:8.1
#    image: orderdesk/php-8.0.3-cli-alpine3.13:latest
#    image: ekinhbayar/php-7.4-alpine3.11-git-gd-intl-composer-tideways_xhprof-phpredis
    build:
      context: ./
      dockerfile: php/Dockerfile7
    container_name: "${PROJECT_NAME}_php"
    environment:
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_DRIVER: "${DB_DRIVER}"
      SITE_URL: "http://${PROJECT_BASE_URL}:${PROJECT_PORT}"
    networks:
      - local
#    ports:
#      - 9001:9000
    volumes:
      - ../:/var/www/xhprof
      - ./database:/database:cached
      - ./traces:/traces

  node:
    build:
      context: ./
      dockerfile: node/Dockerfile
    container_name: "${PROJECT_NAME}_node"
    networks:
      - local
    volumes:
      - ../xhprof_html:/app

  nginx:
#    image: nginx:latest
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    ports:
      - "${PROJECT_PORT}:80"
    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/xhprof.conf:/etc/nginx/conf.d/xhprof.conf
      - ../:/var/www/xhprof
    networks:
      - local

  mariadb:
    image: wodby/mariadb:latest
    container_name: "${PROJECT_NAME}_db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_PORT: "${DB_PORT}"
      MYSQL_INNODB_BUFFER_POOL_SIZE: 5G
      MYSQL_NET_READ_TIMEOUT: 360
      MYSQL_NET_WRITE_TIMEOUT: 360
    networks:
      - local
    volumes:
      - dbdata:/var/lib/mysql
#    ports:
#      - "43306:3306"

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    restart: always
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: "${DB_PORT}"
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASSWORD}"
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
      PMA_ARBITRARY: 1
    networks:
      - local
    ports:
      - "8001:80"

volumes:
  dbdata:

networks:
  local: