<?php

use Xhprof\Utils;

//$view = new XhprofView();
$utils = new Utils();
$report_url = $utils->getReportUrl();

?>

<div class="container">
    <div class="dash-header">
        <div class="xh-title-wrap">
            <a class="xh-title" href="<?php print $report_url; ?>">XH GUI</a>
        </div>

        <div id="options">
            <form name="simple_bar" method="get" action="">
                <label id="format">
                    Format:
                    <select>
                        <option selected>svg</option>
                        <option>png</option>
                        <option>xdot</option>
                        <option>plain</option>
                        <option>ps</option>
                    </select>
                </label>

                <?php include ("internal_functions.phtml"); ?>
                <?php include ("threshold.phtml"); ?>
            </form>
        </div>
    </div>
</div>